// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5mkFUlGT0xfV6Gl0Oj5gRpBHqdy3pfMU',
    appId: '1:399680220385:web:5bf08f3430406abacedba0',
    messagingSenderId: '399680220385',
    projectId: 'filmflicks-cea0e',
    authDomain: 'filmflicks-cea0e.firebaseapp.com',
    storageBucket: 'filmflicks-cea0e.appspot.com',
    measurementId: 'G-5ZDN510XFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZsce9Gr0VM3xlxE7GXXq75hKEcEdVOyY',
    appId: '1:399680220385:android:6667dac23c291defcedba0',
    messagingSenderId: '399680220385',
    projectId: 'filmflicks-cea0e',
    storageBucket: 'filmflicks-cea0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRy33LoE-IZkQYPcna1vM7QTIWVtQAMRE',
    appId: '1:399680220385:ios:d930e65ee531d37ccedba0',
    messagingSenderId: '399680220385',
    projectId: 'filmflicks-cea0e',
    storageBucket: 'filmflicks-cea0e.appspot.com',
    iosBundleId: 'com.example.filmflicks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRy33LoE-IZkQYPcna1vM7QTIWVtQAMRE',
    appId: '1:399680220385:ios:d930e65ee531d37ccedba0',
    messagingSenderId: '399680220385',
    projectId: 'filmflicks-cea0e',
    storageBucket: 'filmflicks-cea0e.appspot.com',
    iosBundleId: 'com.example.filmflicks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5mkFUlGT0xfV6Gl0Oj5gRpBHqdy3pfMU',
    appId: '1:399680220385:web:d1280e69591b594dcedba0',
    messagingSenderId: '399680220385',
    projectId: 'filmflicks-cea0e',
    authDomain: 'filmflicks-cea0e.firebaseapp.com',
    storageBucket: 'filmflicks-cea0e.appspot.com',
    measurementId: 'G-9D40Y31ZDB',
  );
}
